run:
  go: "1.20"
  deadline: 5m
  skip-files:
    - "init.go"
  build-tags:
    - mock
    - integration
linters:
  enable-all: true
  disable:
    # deprecated
    - golint
    - exhaustivestruct
    - maligned
    - interfacer
    - scopelint
    - ifshort
    - varcheck
    - structcheck
    - deadcode
    - nosnakecase
    # ugly
    - varnamelen

    # tmp
    - tagliatelle
    - exhaustruct
    - testpackage
    - unused
    - godox
linters-settings:
  revive:
    rules:
      - name: unexported-return
        disabled: true
  misspell:
    locale: US
  gci:
    sections:
      - Standard
      - Default
  lll:
    line-length: 140
