// Code generated by mockery v2.20.0. DO NOT EDIT.

package service

import (
	model "blynker/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMock is an autogenerated mock type for the ServiceMock type
type ServiceMock struct {
	mock.Mock
}

// GetData provides a mock function with given fields:
func (_m *ServiceMock) GetValues() *model.Sensor {
	ret := _m.Called()

	var r0 *model.Sensor
	if rf, ok := ret.Get(0).(func() *model.Sensor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sensor)
		}
	}

	return r0
}

// SaveData provides a mock function with given fields: sensor
func (_m *ServiceMock) SaveValues(sensor *model.Sensor) error {
	ret := _m.Called(sensor)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Sensor) error); ok {
		r0 = rf(sensor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMock(t mockConstructorTestingTNewService) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
