// Code generated by mockery v2.20.0. DO NOT EDIT.

package service

import (
	"blynker/internal/model"
	"github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type SrvMock struct {
	mock.Mock
}

// GetSensorIDs provides a mock function with given fields:
func (_m *SrvMock) GetSensorIDs() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetValues provides a mock function with given fields:
func (_m *SrvMock) GetValues() *model.Sensor {
	ret := _m.Called()

	var r0 *model.Sensor
	if rf, ok := ret.Get(0).(func() *model.Sensor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sensor)
		}
	}

	return r0
}

// SaveValues provides a mock function with given fields: sensor
func (_m *SrvMock) SaveValues(sensor *model.Sensor) error {
	ret := _m.Called(sensor)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Sensor) error); ok {
		r0 = rf(sensor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMock creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMock(t mockConstructorTestingTNewService) *SrvMock {
	mock := &SrvMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
